name: Go

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: env CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -v -o bin/neoray_linux_386 ./src
