name: Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build amd64
      env: 
        CGO_ENABLED: 1
        GOARCH: amd64
      run: go build -v -ldflags -H=windowsgui -o bin/neoray_win_amd64.exe ./src
      
    - name: Build 386
      env:
        CGO_ENABLED: 1
        GOARCH: 386
      run: go build -v -ldflags -H=windowsgui -o bin/neoray_win_386.exe ./src
