name: Release

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build amd64
      env: 
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: amd64
      run: go build -ldflags -H=windowsgui -o bin/neoray-windows-amd64.exe ./src
    
    - name: Set up MinGW x86
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x86
      
    - name: Build 386
      env:
        CGO_ENABLED: 1
        GOOS: windows
        GOARCH: 386
      run: go build -ldflags -H=windowsgui -o bin/neoray-windows-386.exe ./src

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-binaries
        path: | 
          bin/neoray-windows-amd64.exe
          bin/neoray-windows-386.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build amd64
      env: 
        CGO_ENABLED: 1
        GOOS: darwin
        GOARCH: amd64
      run: go build -o bin/neoray-macos ./src
      
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos-binaries
        path: | 
          bin/neoray-macos
          
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Set up required libs
      run: |
        sudo apt update && sudo apt upgrade
        sudo apt install libx11-dev libgtk-3-dev libgl1-mesa-dev xorg-dev gcc-multilib
        sudo apt install libx11-dev:i386 libgtk-3-dev:i386 libgl1-mesa-dev:i386 xorg-dev:i386

    - name: Build amd64
      env: 
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: amd64
      run: go build -o bin/neoray-linux-amd64 ./src
      
    - name: Build 386
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: 386
      run: go build -o bin/neoray-linux-386 ./src

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: linux-binaries
        path: | 
          bin/neoray-linux-amd64
          bin/neoray-linux-386
          
  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    if: success()
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        
      - name: Deploy latest release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: success()
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            bin/neoray-windows-amd64.exe
            bin/neoray-windows-386.exe
            bin/neoray-macos
            bin/neoray-linux-amd64
            bin/neoray-linux-386
