name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Golang CGO cross compiler
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-xgo@0bf105240c754748ecfb954a003a7e2ad8518a4b
        uses: crazy-max/ghaction-xgo@v1.6.1
        with:
          # xgo version
          #xgo_version: # optional, default is latest
          # Go release to use for cross compilation
          #go_version: # optional, default is latest
          # Destination folder to put binaries in
          dest: bin # optional, default is build
          # Sub-package to build if not root import
          #pkg: # optional
          # Prefix to use for output naming. Default to package name
          #prefix: # optional
          # Comma separated targets to build for. Example: windows/amd64,linux/386
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/amd64 # optional, default is */*
          # Prints the names of packages as they are compiled
          #v: # optional, default is false
          # Prints the build commands as compilation progresses
          x: true # optional, default is false
          # Enable data race detection (supported only on amd64)
          #race: # optional, default is false
          # Comma separated list of build tags to consider satisfied during the build
          #tags: # optional
          # Arguments to pass on each go tool link invocation
          #ldflags: # optional
          # Indicates which kind of object file to build
          #buildmode: # optional, default is default
          # Working directory
          #working_dir: # optional
          # Use custom docker repo instead of official distribution
          #docker-repo: # optional, default is ghcr.io/crazy-max/xgo
      
      - name: print executables
        run: |
          cd bin
          ls -A -l -h --color=auto
